language: python

python:
- '2.7'

sudo: required

services:
- docker

before_install:
- docker version
- sudo apt-get update
- (sleep 5; echo "Y"; sleep 2; echo "Y") |sudo apt-get install -y docker-engine
- docker version
- sudo pip install -U docker-compose
- docker-compose -f ci.docker-compose.yml up -d

script: python -m unittest discover



